
[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#FF7F00"
text = "#2c2c2c"

[font]
size = 13.0

[font.normal]
family = "MesloLGS Nerd Font"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 99999

[window]
decorations = "None"
dynamic_title = true
opacity = 0.95
# blur = true

[window.padding]
x = 8
y = 8

[general]
import = [
    "~/.config/alacritty/themes/themes/dracula-jtp.toml"
]

[[keyboard.bindings]]
key = "G"
mods = "Command"
chars = "\u0007"  # Ctrl-G = ASCII 7

# This will work for the terminal, but it won't be passed to neovim :/
[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[selection]
save_to_clipboard = true
