
[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#FF7F00"
text = "#2c2c2c"

[font.normal]
family = "Liberation Mono"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 99999

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 8
y = 8

[general]
import = [
    "~/.config/alacritty/themes/themes/dracula-jtp.toml"
]
