

draw_bold_text_with_bright_colors: true

# Point size of the font
size: 13.0

# Background opacity
background_opacity: 0.5

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }


hide_cursor_when_typing: false

cursor_style: Block
