[tool.poetry]
name = "dotfiles"
version = "0.1.0"
description = "Manage user environment."
authors = ["John Prince <jtprince@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
