# See installation-initial.md for initial steps
# arch-installer.py --install-subsections user.<whatever>
#
wayland-more:
  - xorg-xwayland
  - wl-clipboard-x11
  - wl-clipboard
  - wlr-randr
  - azote
  # notifications
  - mako
  - grimshot
  - python-i3ipc
  # screen recording
  - wf-recorder
  - waybar
  # for waybar-media (MPRIS compatible)
  - python-pydbus
  # for waybar-media (MPRIS compatible)
  - python-psutil
  - swaylock
  - swaybg
  - wev
  - _post_commands:
    - "wget https://raw.githubusercontent.com/yurihs/waybar-media/master/waybar-media.py --directory-prefix ~/.local/bin"
    - "chmod +x ~/.local/bin/waybar-media.py"
sudo:
  - _post_commands:
    - "sudo mkdir -p /etc/sudoers.d"
    - "sudo cp /home/jtprince/dotfiles/config/sudoers.d/* /etc/sudoers.d/"
    - "sudo chmod 0400 /etc/sudoers.d/*"

plymouth:
  - plymouth
  - plymouth-theme-arch10
  - _post_commands:
    - "sudo $HOME/bin/plymouth-add-boot-params /boot/loader/entries/arch.conf"
    - "sudo $HOME/bin/plymouth-add-mkinitcpio-hook"
    - "sudo plymouth-set-default-theme arch10"
    - "sudo mkinitcpio -P"
neovim:
  - ruff
  - code-minimap
python:
  - pyenv
  - pyenv-virtualenv
  - python-pip
  - python-pipx
  - ipython
  - python-black
  - python-isort
  - python-pynvim
  - python-poetry
  - python-poetry-plugin-up
  - python-ipdb
  - python-nox-poetry
  # - python-pudb
  # for matplotlib (tk to avoid 'No module name '_tkinter')
  - tk
  # not sure if I really need tcl and python-pmw ??
  - tcl
  # for numpy / scipy
  - gcc-fortran
  - python-pmw
  - python-markdown
  - python-pygithub
  - python-ruyaml
  - python-pre-commit
  - python-pandas
  - python-nox
  - python-terminaltables
  - python-pyperclip
  - cruft
  - _post_commands:
    - "mkdir ~/.pyenv"
  - _post_notes:
    - "[THEN LOGIN OUT AND BACK IN!]"
language-servers:
  # see https://wiki.archlinux.org/title/Neovim#Tips_and_tricks
  - pyright
  - rust-analyzer
  - gopls
  - yaml-language-server
  # would like to do solargraph, but giving errors:
  # - ruby-solargraph
security:
  - firejail
application-launcher:
  - tofi
alacritty-themes:
  - _post_commands:
    - "mkdir -p ~/.config/alacritty/themes"
    - "gh repo clone https://github.com/jtprince/alacritty-theme ~/.config/alacritty/themes"
dropbox:
  - dropbox
  - dropbox-cli
  - _post_commands:
    - dropbox
  - _post_notes:
    - "and follow instructions in browser"
    - "dropbox-cli status to see where things are at"
    - "be patient after inital linkage"
pipewire-screenshare:
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
networking:
  - network-manager-applet
  - networkmanager-openvpn
  - dnsutils   # for getting wan ip address
nvim-related:
  - git-delta
package-managers:
  - paru-bin
firefox-config:
  # With these profiles (also in sway bindings and launch email):
  # -P personal
  # -P work
  - _post_notes:
    - "Goto: about:config"
    - "mousewheel.default.delta_multiplier_y 66"
ntp:
  # archinstall says it does ntp, but it's not installed
  - ntp
  - tzupdate
  - _post_commands:
    - "sudo systemctl enable --now ntpd.service"
keychain-more:
  - docker-credential-secretservice-bin
files:
  - thunar
  - gvfs
  - gvfs-mtp
  - udisks
  - tree
  # common file system stuff
  - ntfs-3g
  - trash-cli
  # extraction, search, backups
  - dtrx
  - zip
  - ack
  - ripgrep
  - ack
  - unrar
  - unrpa
  - dragon-drop
  - fd
  - meld
  # ranger and deps
  - ranger
  - atool
  - highlight
  - mediainfo
  - odt2txt
  - perl-image-exiftool
  - transmission-cli
  - w3m
  - libcaca
  # ncurses disk usage (faster/better filelite)
  - ncdu
install-python-versions:
  - _post_notes:
    - "pyenv install --list"
    - "[UPDATE YOUR VERSIONS!!!]"
    - 'CONFIGURE_OPTS="--enable-shared --enable-loadable-sqlite-extensions --with-system-ffi --with-ensurepip=upgrade --enable-optimizations"'
    - "pyenv install 3.9.18"
    - "pyenv install 3.10.13"
    - "pyenv install 3.11.7"
    - "pyenv install 3.12.1"
jupyter:
  - jupyterlab
  - python-jupytext
ruby:
  # probably already installed
  - openssl
  # pry likes readline
  - readline
  - zlib
  - ruby
  - rbenv
  - ruby-build
  - ruby-mustache
  - neovim
  - _post_notes:
    - "rbenv install --list"
    - "rbenv install --list-all"
    - "CONFIGURE_OPTS=\"--with-readline-dir=/usr/include/readline\""
    - "rbenv install <SOME_VERSION>"
    - "rbenv global <SOME_VERSION>"
    - "gem install pry clipboard solargraph"
notifications:
  - mako
  - python-mako
sound:
  # Should have already been installed:
  - pipewire-pulse
  - pipewire-alsa
  - pasystray-git
  - pavucontrol
  - python-pulsectl
  - paprefs
  - pavumeter
  - noise-suppression-for-voice
  - _post_commands:
    - "systemctl --user enable --now pipewire-pulse.service"
  - _post_notes:
    - "check with: "
    - "systemctl --user status pipewire-pulse.service"
    - "and: "
    - "pactl info"
speech:
  # for discord speech output
  - speech-dispatcher
  # a voice for speech-dispatcher
  - espeakup
bluetooth:
  - bluez
  - bluez-utils
  - blueman
theme:
  - gnome-themes-standard
font:
  # core fonts
  # patched dejavu to include tons of nerd icons
  # - ttf-dejavu-nerd  # installed very early as main terminal font
  - ttf-roboto
  - ttf-ubuntu-font-family
  # standard fonts
  # - noto-fonts  # installed very early as viable kitty font
  - noto-fonts-emoji
  - noto-fonts-cjk
  - ttf-ms-fonts
  - ttf-tahoma
  - ttf-liberation
  - ttf-symbola
  # vim powerline
  - powerline-fonts-git
  # font for status bar
  - ttf-font-icons
  # font for fim (see FBFONT in profile)
  - terminus-font
  # font with great icon support (essential for waybar)
  - otf-font-awesome
  # misc
  - otf-ipafont
  - culmus
  - cantarell-fonts
  - _post_commands:
    # link my own batch of fonts
    - "ln -s ~/Dropbox/env/appearance/fonts/dot-fonts ~/.local/share/fonts"
    - "fc-cache"
    - "ls -alh /etc/fonts/conf.d/"
    ## Ensure good font settings
    - "echo 'expecting 10-hinting-slight.conf 10-sub-pixel-rgb.conf 11-lcdfilter-default.conf'"
# apparmor:
    # !! Add kernel params to boot: lsm=landlock,lockdown,yama,integrity,apparmor,bpf
    # - _post_commands:
      # - "systemctl enable --now apparmor.service"
screenshots:
  # for screenshot OCR
  - python-pytesseract
  - tesseract-data-eng
configure-backlight:
  - _post_commands:
    # See your options for backlight:
    - "ls /sys/class/backlight"
  - _post_notes:
    - "the commenting escaping is hard to get right here, so leaving as # comment:"
    - >
      sudo sh -c 'echo "export BACKLIGHT=\"<GET THIS RIGHT>\"" > /etc/profile.d/backlight.sh'
sad:
  - sad
file-utils:
  - mlocate
  - pkgfile
  # for paccache
  - pacman-contrib
  - _post_commands:
    - "sudo updatedb"
    - "sudo pkgfile --update"
pdf:
  - pdftk
  - evince
  - _post_commands:
    # zooming is restricted by page cache size, increase to get zoom into large docs
    - "gsettings set org.gnome.Evince page-cache-size 2014"
media:
  - avizo
  - pamixer
  - ncspot-cover
  - playerctl
  # - xava
  - archey3
  - feh
  # mplayer that works with wayland
  - mpv
  # dbus interface to control with playerctl
  - mpv-mpris
  - inkscape
  - gimp
  - eog
  - imv
  # - nomacs  ## < - takes forever to install, install on demand
  - xnviewmp
  - youtube-dl
  - pandoc-bin
  - mp3splt
  - audacity
  - satty
  - imagemagick
office:
  # - slack-wayland
  - zoom
libre-office:
  - libreoffice
  - libmythes
  - mythes-en
  - unoconv
system-monitoring:
  - gnome-system-monitor
  - gnome-power-manager
  - libstatgrab
  - pystatgrab
cheat-sheets:
  - cheat-bin
  - _post_commands:
    - "mkdir -p src && cd src && gh repo clone cheat/cheatsheets && cd"
display-manager:
  - lemurs
  - _post_commands:
    - sudo systemctl enable lemurs.service
    - sudo gpasswd -a jtprince seat
    - sudo mkdir /etc/lemurs/wayland
    - echo '#!/bin/sh' | sudo tee -a /etc/lemurs/wayland/sway
    - echo "exec sway" | sudo tee -a /etc/lemurs/wayland/sway
    - sudo chmod +x /etc/lemurs/wayland/sway
laptop:
  - acpi
  # using tlp for battery optimizations
  # follow instructions here: https://linrunner.de/tlp/installation/arch.html
  # Should be roughly
  - tlp
  - tlp-rdw
  - post_notes:
    - "then run this to know which other packages to install for the system"
    - "sudo tlp-stat -b"
    - "# e.g., `acpi_call`"
  # sudo systemctl enable --now tlp.service
  # ### The below were problematic ---->> [maybe don't do the below??]
  # ### sudo systemctl enable --now NetworkManager-dispatcher.service
  # sudo systemctl mask systemd-rfkill.service
  # sudo systemctl mask systemd-rfkill.socket


##############
## OPTIONAL ##
##############
dns-lookup:
  # enable dnsmasq to shorten dns lookup
  # WARNING!!! BE AWARE that this can interfere with cloudflare warp
  # So, turn it off if you are getting a can't connect on port 53 error
  - dnsmasq
  - _post_commands:
    - echo "listen-address=::1,127.0.0.1" | sudo tee --append /etc/dnsmasq.conf
    - "sudo systemctl enable --now dnsmasq.service"
printing:
  - cups
  - cups-pdf
  # For cups recognition of network printers:
  - avahi
  - nss-mdns
  - brother-hll2350dw
  - system-config-printer
  # - hplip
  - _post_commands:
    - sudo systemctl enable --now avahi-deamon.service
    # Will automatically turn on cups service when applicable ports requested:
    -  sudo systemctl enable --now cups.socket
  - _post_notes:
    #   hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns
    - Edit /etc/nsswitch.conf and change `hosts` line to include `mdns_minimal [NOTFOUND=return]`
    - Then
    - sudo systemctl start cups.service
    - system-config-printer
android:
  - jmtpfs
  # mkdir ~/mnt
  # Once you have connected the phone by USB, then
  # select 'Use USB for' -> 'File transfer / Android Auto'
  # to mount phone once you've plugged it into usb:
  # jmtpfs ~/mnt
cloud-cli:
  - aws-cli
  # - google-cloud-sdk
docker:
  - docker
  - docker-compose
  - _post_commands:
    - "sudo gpasswd -a jtprince docker"
    - "sudo systemctl enable docker.service"
secondary-browser:
  - google-chrome
  - midori
github:
  - github-cli ## installed very early now
misc:
  # for password generation
  - words
  # torrents
  - deluge-gtk
  # read your bios version (sudo dmidecode -s bios-version)
  - dmidecode
  - _post_commands:
    - "python ~/Dropbox/backgrounds/create-png-background-folder"
polkit:
  # Did not install this on acer this last time? Did pip install work
  # properly??
  - polkit-dumb-agent
music:
  - _pre_commands:
    - "curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg  | gpg --import -"
  - ncspot
  - spotify
# informant:
  # ensure arch news is read
  # - informant
wine:
  - wine-staging
  - wine-gecko
  - wine-mono
  # for gaming in wine (necessary fonts already installed)
  - lib32-alsa-lib
  - lib32-alsa-plugins
  - lib32-libpulse
  - lib32-alsa-oss
  - lib32-openal
  - lib32-libxml2
  - lib32-mpg123
  - lib32-lcms2
  - lib32-giflib
  - lib32-libpng
  - lib32-gnutls
  - lib32-virtualgl
  - lib32-libldap
  - _post_commands:
    - "winecfg"
  - _post_notes:
    - "go to staging tab and click Enable_CSMT for better graphic performance"
texlive-fonts:
  # texlive fonts (needed for pandoc pdf conversion)
  # texlive-latexextra needed for etoolbox.sty, and other md->pdf goodies
  - texlive-core
  - texlive-fontsextra
  - texlive-latexextra
  - _post_commands:
    - "sudo ln -s /etc/fonts/conf.avail/09-texlive-fonts.conf /etc/fonts/conf.d/09-texlive-fonts.conf"
    - "sudo fc-cache && sudo mkfontscale && sudo mkfontdir && sudo rm -f fonts.dir fonts.scale"

