[directory]
truncate_to_repo = true
truncation_length = 0

[time]
disabled = true
format = "[$time]($style) "

[username]
show_always = false

style_user = "green"
style_root = "red bold"

[python]
# Only show if inside a Python project
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "requirements.txt", ".python-version"]
detect_folders = []

# Don't show the Python version
pyenv_version_name = false
version_format = ""  # empty means: skip showing the version

# Custom format: just show the virtualenv name
format = "via 🐍 [$virtualenv]($style) "
