#!/bin/sh

# system X11 xinitrc files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# xprofile
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

export XDG_SESSION_TYPE=x11
export DEFAULT_SESSION=i3

exec i3
#exec i3 -V -d all >~/.config/i3/i3log-$(date +'%F-%k-%M-%S') 2>&1

# exec startlxde
# exec gnome-session
# exec startkde
# exec startxfce4

